// Auto-generated build information
// DO NOT EDIT THIS FILE MANUALLY
// Generated at: 2026-02-12T11:53:57.423Z

export const BUILD_INFO = {
    version: "0.0.87",
    buildTimestamp: "2026-02-12T11:53:57.423Z",
    buildNumber: 1770897237424,
    gitCommit: "c712b51",
} as const;

export function getBuildInfo(): string {
    return `Log Scout Analyzer v${BUILD_INFO.version} (build ${BUILD_INFO.buildNumber})`;
}

export function getDetailedBuildInfo(): string {
    return [
        `Version: ${BUILD_INFO.version}`,
        `Build: ${BUILD_INFO.buildTimestamp}`,
        `Build #: ${BUILD_INFO.buildNumber}`,
        `Git: ${BUILD_INFO.gitCommit}`,
    ].join('\n');
}
