// Auto-generated build information
// DO NOT EDIT THIS FILE MANUALLY
// Generated at: 2026-02-24T15:15:08.458Z

export const BUILD_INFO = {
    version: "0.0.194",
    buildTimestamp: "2026-02-24T15:15:08.458Z",
    buildNumber: 1771946108459,
    gitCommit: "cd10c7e",
} as const;

export function getBuildInfo(): string {
    return `Log Scout Analyzer v${BUILD_INFO.version} (build ${BUILD_INFO.buildNumber})`;
}

export function getDetailedBuildInfo(): string {
    return [
        `Version: ${BUILD_INFO.version}`,
        `Build: ${BUILD_INFO.buildTimestamp}`,
        `Build #: ${BUILD_INFO.buildNumber}`,
        `Git: ${BUILD_INFO.gitCommit}`,
    ].join('\n');
}
