// Auto-generated build information
// DO NOT EDIT THIS FILE MANUALLY
// Generated at: 2026-02-08T02:44:31.130Z

export const BUILD_INFO = {
    version: "0.0.18",
    buildTimestamp: "2026-02-08T02:44:31.130Z",
    buildNumber: 1770518671130,
    gitCommit: "b7f7d6a",
} as const;

export function getBuildInfo(): string {
    return `Log Scout Analyzer v${BUILD_INFO.version} (build ${BUILD_INFO.buildNumber})`;
}

export function getDetailedBuildInfo(): string {
    return [
        `Version: ${BUILD_INFO.version}`,
        `Build: ${BUILD_INFO.buildTimestamp}`,
        `Build #: ${BUILD_INFO.buildNumber}`,
        `Git: ${BUILD_INFO.gitCommit}`,
    ].join('\n');
}
