#!/usr/bin/env node

/**
 * Increment Version Script
 * Automatically increments the patch version (third octet) in both:
 * - package.json (extension version)
 * - lsp-server/Cargo.toml (LSP server version)
 *
 * Also:
 * - Generates buildInfo.ts with version and git commit
 * - Calculates hash of files being packaged
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { execSync } = require("child_process");

const packagePath = path.join(__dirname, "package.json");
const cargoPath = path.join(__dirname, "..", "lsp-server", "Cargo.toml");

try {
  console.log("🔄 Incrementing versions...\n");

  // ===== INCREMENT EXTENSION VERSION (package.json) =====
  const packageJson = JSON.parse(fs.readFileSync(packagePath, "utf8"));

  // Parse current extension version
  const extVersionParts = packageJson.version.split(".");
  if (extVersionParts.length !== 3) {
    console.error("❌ Invalid extension version format. Expected x.y.z");
    process.exit(1);
  }

  const extMajor = parseInt(extVersionParts[0]);
  const extMinor = parseInt(extVersionParts[1]);
  const extPatch = parseInt(extVersionParts[2]);

  // Increment patch version
  const newExtPatch = extPatch + 1;
  const newExtVersion = `${extMajor}.${extMinor}.${newExtPatch}`;

  // Update version in package.json
  packageJson.version = newExtVersion;

  // Write back to package.json with proper formatting
  fs.writeFileSync(
    packagePath,
    JSON.stringify(packageJson, null, 4) + "\n",
    "utf8",
  );

  console.log("📦 Extension Version:");
  console.log(`   Old: ${extMajor}.${extMinor}.${extPatch}`);
  console.log(`   New: ${newExtVersion}`);
  console.log("");

  // ===== INCREMENT LSP SERVER VERSION (Cargo.toml) =====
  if (!fs.existsSync(cargoPath)) {
    console.warn(
      "⚠️  Cargo.toml not found, skipping LSP server version increment",
    );
    console.warn(`   Expected at: ${cargoPath}`);
  } else {
    let cargoToml = fs.readFileSync(cargoPath, "utf8");

    // Find the version line
    const versionMatch = cargoToml.match(/version\s*=\s*"([^"]+)"/);

    if (!versionMatch) {
      console.error("❌ Could not parse version from Cargo.toml");
      process.exit(1);
    }

    const lspVersion = versionMatch[1];
    const lspVersionParts = lspVersion.split(".");

    if (lspVersionParts.length !== 3) {
      console.error("❌ Invalid LSP server version format. Expected x.y.z");
      process.exit(1);
    }

    const lspMajor = parseInt(lspVersionParts[0]);
    const lspMinor = parseInt(lspVersionParts[1]);
    const lspPatch = parseInt(lspVersionParts[2]);

    // Increment patch version
    const newLspPatch = lspPatch + 1;
    const newLspVersion = `${lspMajor}.${lspMinor}.${newLspPatch}`;

    // Replace the version in Cargo.toml
    cargoToml = cargoToml.replace(
      /version\s*=\s*"[^"]+"/,
      `version = "${newLspVersion}"`,
    );

    // Write back to Cargo.toml
    fs.writeFileSync(cargoPath, cargoToml, "utf8");

    console.log("🦀 LSP Server Version:");
    console.log(`   Old: ${lspVersion}`);
    console.log(`   New: ${newLspVersion}`);
    console.log("");
  }

  console.log("✅ Version increment complete!");
  console.log("");

  // ===== GENERATE BUILD INFO =====
  console.log("🔨 Generating build info...");

  const buildInfoPath = path.join(__dirname, "src", "buildInfo.ts");
  const buildTimestamp = new Date().toISOString();
  const buildNumber = Date.now();

  // Get git commit hash
  let gitCommit = "unknown";
  try {
    gitCommit = execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim();
  } catch (error) {
    console.warn("⚠️  Could not get git commit hash");
  }

  const buildInfoContent = `// Auto-generated build information
// DO NOT EDIT THIS FILE MANUALLY
// Generated at: ${buildTimestamp}

export const BUILD_INFO = {
    version: "${newExtVersion}",
    buildTimestamp: "${buildTimestamp}",
    buildNumber: ${buildNumber},
    gitCommit: "${gitCommit}",
} as const;

export function getBuildInfo(): string {
    return \`Log Scout Analyzer v\${BUILD_INFO.version} (build \${BUILD_INFO.buildNumber})\`;
}

export function getDetailedBuildInfo(): string {
    return [
        \`Version: \${BUILD_INFO.version}\`,
        \`Build: \${BUILD_INFO.buildTimestamp}\`,
        \`Build #: \${BUILD_INFO.buildNumber}\`,
        \`Git: \${BUILD_INFO.gitCommit}\`,
    ].join('\\n');
}
`;

  fs.writeFileSync(buildInfoPath, buildInfoContent, "utf8");
  console.log(`   ✓ Build info generated: ${buildInfoPath}`);
  console.log(`   Version: ${newExtVersion}`);
  console.log(`   Build: ${buildTimestamp}`);
  console.log(`   Git: ${gitCommit}`);
  console.log("");

  // ===== CALCULATE FILE HASHES =====
  console.log("🔐 Calculating file hashes...");

  const filesToHash = [
    { path: path.join(__dirname, "src", "extension.ts"), name: "extension.ts" },
    { path: path.join(__dirname, "src", "bundleTreeProvider.ts"), name: "bundleTreeProvider.ts" },
    { path: buildInfoPath, name: "buildInfo.ts" },
  ];

  const hashes = {};
  for (const file of filesToHash) {
    if (fs.existsSync(file.path)) {
      const content = fs.readFileSync(file.path);
      const hash = crypto.createHash("sha256").update(content).digest("hex");
      hashes[file.name] = hash.substring(0, 16);
      console.log(`   ${file.name}: ${hash.substring(0, 16)}...`);
    }
  }

  // Save hashes to a manifest file
  const manifestPath = path.join(__dirname, "build-manifest.json");
  const manifest = {
    version: newExtVersion,
    buildNumber: buildNumber,
    buildTimestamp: buildTimestamp,
    gitCommit: gitCommit,
    fileHashes: hashes,
  };

  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), "utf8");
  console.log(`   ✓ Build manifest: ${manifestPath}`);
  console.log("");

  console.log("✅ Version increment and build preparation complete!");
  console.log("");
} catch (error) {
  console.error("❌ Error incrementing version:", error.message);
  process.exit(1);
}
